<?php
session_start();
//定数
require_once('const.php');
//データベース接続系
require_once('dbConst.php');
require_once('Model.php');
//メール送信
require_once('SendMail.php');
//他ファンクション
require_once('util.inc.php');
